server:
  port: 8001
  
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: ABC-SERVICE  # ==> This is a instance of ABC-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      #      defaultZone: http://my-eureka-server.com:9000/eureka
      defaultZone: http://my-eureka-server-us.com:9000/eureka
#      defaultZone: http://my-eureka-server-fr.com:9002/eureka
#      defaultZone: http://my-eureka-server-vn.com:9003/eureka
spring:
  application:
    name: ABC-SERVICE